#!/bin/bash


#./gradlew installDebug  &&
#./gradlew clean &&
#./gradlew assembleDebug &&
#adb -s "03bc644502a26414" uninstall com.futcore.restaurant &&
sudo /home/yanjzhou/Software/bin/android-sdk-linux/platform-tools/adb -s "14392D27F246534" install -r ./Wearable/build/apk/Wearable-debug-unaligned.apk  &&
#sudo /home/yanjzhou/Software/bin/android-sdk-linux/platform-tools/adb -s "14392D27F246534" install ./Wearable/build/apk/Wearable-debug-unaligned.apk  &&
sudo /home/yanjzhou/Software/bin/android-sdk-linux/platform-tools/adb -s "14392D27F246534" shell am start -n com.example.android.wearable.gridviewpager/.MainActivity &&
sudo /home/yanjzhou/Software/bin/android-sdk-linux/platform-tools/adb -s "14392D27F246534" logcat

#adb -s localhost:4444 install ./Wearable/build/apk/Wearable-debug-unaligned.apk
#/home/yanjzhou/Software/bin/adt-bundle-linux-x86_64-20140321/sdk/platform-tools/adb -s localhost:4444  shell am start -n com.example.android.wearable.gridviewpager/.MainActivity &&
#/home/yanjzhou/Software/bin/adt-bundle-linux-x86_64-20140321/sdk/platform-tools/adb -s localhost:4444 logcat




